#' Prepare directories for the analysis
home <- path_home()
work.dir <- paste(home, "OVisium", sep = "/")
sr.dir <- paste(work.dir, "Spaceranger", sep = "/")
qc.dir <- paste(work.dir, "QC", sep = "/")
anno.dir <- paste(work.dir, "Annotation", sep = "/")
rds.dir <- paste(work.dir, "SCT_RDS", sep = "/")
dims.dir <- paste(work.dir, "Dims_reduction", sep = "/")
deg.dir <- paste(work.dir, "DE_functional_analysis", sep = "/")
dec.dir <- paste(work.dir, "Deconvolution_analysis", sep = "/")

dir.create(work.dir, recursive = T)
dir.create(sr.dir, recursive = T)
dir.create(qc.dir, recursive = T)
dir.create(anno.dir, recursive = T)
dir.create(rds.dir, recursive = T)
dir.create(dims.dir, recursive = T)
dir.create(deg.dir, recursive = T)
dir.create(dec.dir, recursive = T)

setwd("~/OVisium")
